"""
Analysis Executor module for the AutoInterp Agent Framework.
Securely executes analysis scripts generated by the Analysis Generator,
captures outputs, and structures results for consumption by the Evaluator.
"""

import os
import sys
import json
import time
import asyncio
import traceback
import re  # For parsing TXT files
import shutil
from pathlib import Path
from typing import Dict, List, Any, Optional, Union, Tuple
import logging
import subprocess
import io
import textwrap

from ..core.utils import (
    get_timestamp,
    format_time_elapsed,
    install_requirements,
    execute_in_virtual_env,
    PathResolver,
    clean_code_content,
    ensure_directory
)


def _detect_container_runtime(config: Dict[str, Any]) -> Optional[str]:
    """
    Detect which container runtime to use based on config and system availability.

    Reads ``execution.docker.runtime`` (default ``"auto"``).
    * ``"auto"`` — try ``docker`` first, then ``podman``
    * ``"docker"`` / ``"podman"`` — check only that binary

    Returns:
        ``"docker"``, ``"podman"``, or ``None`` if nothing is found.
    """
    runtime_pref = (
        config.get("execution", {}).get("docker", {}).get("runtime", "auto")
    )
    if runtime_pref == "auto":
        for candidate in ("docker", "podman"):
            if shutil.which(candidate):
                return candidate
        return None
    # Explicit choice
    if shutil.which(runtime_pref):
        return runtime_pref
    return None


def _is_selinux_enforcing() -> bool:
    """Return ``True`` when SELinux is in Enforcing mode (Fedora/RHEL/CentOS).

    Returns ``False`` on non-SELinux systems or when ``getenforce`` is absent.
    """
    try:
        result = subprocess.run(
            ["getenforce"], capture_output=True, text=True, timeout=5
        )
        return result.returncode == 0 and result.stdout.strip() == "Enforcing"
    except (FileNotFoundError, subprocess.TimeoutExpired):
        return False


def check_docker_sandbox(config: Dict[str, Any]) -> None:
    """
    Check if Docker is available when sandbox mode is enabled.
    Prompts the user once at startup and updates config in-memory.
    Call this before any AnalysisExecutor is created.
    """
    execution_mode = config.get("execution", {}).get("mode", "sandbox")
    analysis_execution = config.get("analysis", {}).get("execution", {})
    sandbox_enabled = bool(analysis_execution.get("sandbox")) and execution_mode == "sandbox"

    if not sandbox_enabled:
        return

    runtime = _detect_container_runtime(config)
    if runtime:
        # Store resolved runtime so downstream code can use it without re-detecting
        config.setdefault("execution", {}).setdefault("docker", {})["_resolved_runtime"] = runtime
        return

    # No container runtime found — prompt user
    print("\n" + "=" * 60)
    print("CONTAINER RUNTIME NOT FOUND")
    print("=" * 60)
    print("A container runtime (Docker or Podman) is required for sandbox mode")
    print("but neither was found on your system.")
    print("Sandbox mode provides security isolation when executing AI-generated code.")
    print()

    while True:
        print("What would you like to do?")
        print("1. Install a container runtime (get installation instructions)")
        print("2. Proceed without sandboxing (disable sandbox mode)")
        print("3. Exit")
        print()

        try:
            choice = input("Please select an option (1-3): ").strip()
        except (EOFError, KeyboardInterrupt):
            print("\nExiting...")
            sys.exit(1)

        if choice == "1":
            _show_docker_installation_instructions()
            print("\nAfter installing Docker or Podman, please restart the AutoInterp system.")
            sys.exit(0)
        elif choice == "2":
            saved = _disable_sandbox_in_file()
            print("\n" + "=" * 60)
            print("SANDBOX MODE DISABLED")
            print("=" * 60)
            if saved:
                print("Sandbox mode has been disabled in your config.yaml file.")
            else:
                print("Could not update config.yaml (read-only or permissions issue).")
                print("Sandbox is disabled for this session only.")
            print("Code will now execute directly in your Python environment.")
            print("=" * 60)
            print()

            # Update config in-memory so no AnalysisExecutor triggers the check again
            config.setdefault("analysis", {}).setdefault("execution", {})["sandbox"] = False
            return
        elif choice == "3":
            print("Exiting...")
            sys.exit(0)
        else:
            print("Invalid choice. Please select 1, 2, or 3.")
            print()


def _disable_sandbox_in_file() -> bool:
    """Try to persist sandbox=false to config.yaml. Returns True on success."""
    try:
        import yaml
        config_path = Path(__file__).resolve().parents[2] / "config.yaml"
        if not config_path.exists():
            return False
        with open(config_path, "r") as f:
            config_data = yaml.safe_load(f)
        config_data.setdefault("analysis", {}).setdefault("execution", {})["sandbox"] = False
        with open(config_path, "w") as f:
            yaml.dump(config_data, f, default_flow_style=False, sort_keys=False)
        return True
    except Exception:
        return False


def _show_docker_installation_instructions():
    """Display Docker/Podman installation instructions for different operating systems."""
    import platform

    print("\n" + "=" * 60)
    print("CONTAINER RUNTIME INSTALLATION INSTRUCTIONS")
    print("=" * 60)

    system = platform.system().lower()

    if system == "linux":
        print("Option A — Docker (Ubuntu/Debian):")
        print("   sudo apt-get update && sudo apt-get install docker.io")
        print("   sudo systemctl start docker && sudo systemctl enable docker")
        print("   sudo usermod -aG docker $USER  # optional, run without sudo")
        print()
        print("Option B — Podman (Fedora/RHEL/CentOS):")
        print("   sudo dnf install podman")
        print()
        print("   Ubuntu/Debian:")
        print("   sudo apt-get update && sudo apt-get install podman")
        print()
        print("For other distributions:")
        print("   Docker:  https://docs.docker.com/engine/install/")
        print("   Podman:  https://podman.io/docs/installation")
    elif system == "darwin":
        print("Option A — Docker Desktop:")
        print("   brew install --cask docker")
        print("   # or download from https://www.docker.com/products/docker-desktop")
        print()
        print("Option B — Podman:")
        print("   brew install podman")
        print("   podman machine init && podman machine start")
    elif system == "windows":
        print("Option A — Docker Desktop:")
        print("   Download from https://www.docker.com/products/docker-desktop")
        print("   Note: requires Windows 10/11 with WSL2 enabled")
        print()
        print("Option B — Podman Desktop:")
        print("   Download from https://podman-desktop.io/")
    else:
        print(f"For {system}:")
        print("   Docker: https://docs.docker.com/engine/install/")
        print("   Podman: https://podman.io/docs/installation")

    print()
    print("After installation, verify your runtime:")
    print("   docker --version   # or")
    print("   podman --version")
    print("=" * 60)

class AnalysisExecutor:
    """
    Executes analysis scripts in a secure environment.
    
    Responsibilities:
    - Safely execute analysis code
    - Capture outputs and results
    - Handle errors gracefully
    - Structure results for evaluator consumption
    - Provide metrics on execution time and resource usage
    """
    
    # Standard imports to prepend to all analysis scripts
    STANDARD_IMPORTS = """import logging
# Import required packages
import numpy as np
import torch
# Suppress CUDA NVML warnings
import warnings
warnings.filterwarnings("ignore", "Can't initialize NVML")

import transformers
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import scipy
import sklearn
from sklearn import metrics, decomposition
from tqdm.auto import tqdm
import einops
import os
import sys
import json
import random

# Set environment variables
os.environ["TOKENIZERS_PARALLELISM"] = "false"

# Original script begins below
"""
    
    def __init__(self, config: Dict[str, Any]):
        """
        Initialize the Analysis Executor.
        
        Args:
            config: Configuration dictionary
        """
        self.config = config
        
        # Use the PathResolver singleton instead of storing project_id directly
        self.path_resolver = PathResolver(config)
        
        # Log initialization with path resolver
        logger = logging.getLogger("autointerp.analysis_executor")
        logger.info(f"AnalysisExecutor initialized using path resolver with project_id: {self.path_resolver.project_id}")
        
        # Ensure all required directories exist
        self.path_resolver.ensure_path("visualizations")
        self.path_resolver.ensure_path("reports")
        self.path_resolver.ensure_path("analysis")
        self.path_resolver.ensure_path("evaluation_results")
        
        # Set up execution environment options
        self.execution_mode = config.get("execution", {}).get("mode", "sandbox")
        self.execution_timeout = config.get("execution", {}).get("timeout", 300)  # 5 minutes default
        self.max_memory = config.get("execution", {}).get("max_memory_mb", 1024)  # 1GB default
        
        # Configure logging
        self.logger = logging.getLogger("autointerp.analysis_executor")
        
        # Set env_path to None initially - we'll set it up on first use
        self.env_path = None

        # Docker sandbox configuration
        analysis_execution = config.get("analysis", {}).get("execution", {})
        self.sandbox_enabled = bool(analysis_execution.get("sandbox")) and self.execution_mode == "sandbox"
        docker_settings = config.get("execution", {}).get("docker", {})
        self.docker_image = docker_settings.get("image", "python:3.10-slim")
        self.docker_extra_args = docker_settings.get("extra_args", [])
        self.docker_use_gpu = docker_settings.get("use_gpu", False)
        self.docker_env_passthrough = docker_settings.get("env", [])
        cache_root_default = Path.home() / ".autointerp" / "docker_cache"
        self.docker_cache_root = Path(docker_settings.get("cache_dir", cache_root_default)).expanduser().resolve()
        self.docker_cache_root.mkdir(parents=True, exist_ok=True)
        self.docker_requirements_target = self.docker_cache_root / "site-packages"
        self.docker_requirements_target.mkdir(parents=True, exist_ok=True)
        self.docker_requirements_sentinel = self.docker_cache_root / "requirements_installed.flag"
        self.repo_root = Path(__file__).resolve().parents[1]
        self.host_home = Path.home().resolve()
        self.hf_cache_dir = Path(os.environ.get("HF_HOME", self.host_home / ".cache" / "huggingface")).resolve()
        self.transformers_cache_dir = Path(os.environ.get("TRANSFORMERS_CACHE", self.hf_cache_dir)).resolve()
        self.pip_cache_dir = Path(os.environ.get("PIP_CACHE_DIR", self.host_home / ".cache" / "pip")).resolve()
        self.torch_cache_dir = Path(os.environ.get("TORCH_HOME", self.host_home / ".cache" / "torch")).resolve()
        requirements_config_path = config.get("paths", {}).get("requirements")
        if requirements_config_path:
            req_path = Path(requirements_config_path)
            if not req_path.is_absolute():
                req_path = (self.repo_root / req_path).resolve()
        else:
            req_path = self.repo_root / "requirements.txt"
        self.requirements_file = req_path.resolve()
        self.logger.info(
            f"AnalysisExecutor requirements file set to: {self.requirements_file} "
            f"(exists={self.requirements_file.exists()})"
        )
        
        # Resolve container runtime (Docker or Podman)
        self.container_runtime = (
            docker_settings.get("_resolved_runtime")
            or _detect_container_runtime(self.config)
        )
        self.is_podman = self.container_runtime == "podman"
        self.selinux_enforcing = self.is_podman and _is_selinux_enforcing()

        if self.sandbox_enabled:
            if self.container_runtime:
                self.logger.info(
                    f"Container sandbox enabled using {self.container_runtime}, image: {self.docker_image}"
                    + (", SELinux :z mounts active" if self.selinux_enforcing else "")
                )
            else:
                # check_docker_sandbox() should have been called earlier;
                # if we still get here, just disable silently.
                self.logger.warning("No container runtime found — disabling sandbox")
                self.sandbox_enabled = False

    def _handle_docker_not_found(self):
        """
        Handle the case when no container runtime is found but sandbox mode is enabled.
        Provides interactive options to install Docker/Podman or proceed without sandboxing.
        """
        import sys

        print("\n" + "="*60)
        print("CONTAINER RUNTIME NOT FOUND")
        print("="*60)
        print("A container runtime (Docker or Podman) is required for sandbox mode")
        print("but neither was found on your system.")
        print("Sandbox mode provides security isolation when executing AI-generated code.")
        print()

        while True:
            print("What would you like to do?")
            print("1. Install a container runtime (get installation instructions)")
            print("2. Proceed without sandboxing (disable sandbox mode)")
            print("3. Exit")
            print()

            try:
                choice = input("Please select an option (1-3): ").strip()
            except (EOFError, KeyboardInterrupt):
                print("\nExiting...")
                sys.exit(1)

            if choice == "1":
                self._show_docker_installation_instructions()
                print("\nAfter installing Docker or Podman, please restart the AutoInterp system.")
                sys.exit(0)
            elif choice == "2":
                saved = self._disable_sandbox_mode()
                print("\n" + "="*60)
                print("SANDBOX MODE DISABLED")
                print("="*60)
                if saved:
                    print("Sandbox mode has been disabled in your config.yaml file.")
                else:
                    print("Could not update config.yaml (read-only or permissions issue).")
                    print("Sandbox is disabled for this session only.")
                print("Code will now execute directly in your Python environment.")
                print("="*60)
                print()

                self.sandbox_enabled = False
                return
            elif choice == "3":
                print("Exiting...")
                sys.exit(0)
            else:
                print("Invalid choice. Please select 1, 2, or 3.")
                print()

    def _show_docker_installation_instructions(self):
        """
        Display Docker/Podman installation instructions for different operating systems.
        """
        import platform

        print("\n" + "="*60)
        print("CONTAINER RUNTIME INSTALLATION INSTRUCTIONS")
        print("="*60)

        system = platform.system().lower()

        if system == "linux":
            print("Option A — Docker (Ubuntu/Debian):")
            print("   sudo apt-get update && sudo apt-get install docker.io")
            print("   sudo systemctl start docker && sudo systemctl enable docker")
            print("   sudo usermod -aG docker $USER  # optional, run without sudo")
            print()
            print("Option B — Podman (Fedora/RHEL/CentOS):")
            print("   sudo dnf install podman")
            print()
            print("   Ubuntu/Debian:")
            print("   sudo apt-get update && sudo apt-get install podman")
            print()
            print("For other distributions:")
            print("   Docker:  https://docs.docker.com/engine/install/")
            print("   Podman:  https://podman.io/docs/installation")

        elif system == "darwin":  # macOS
            print("Option A — Docker Desktop:")
            print("   brew install --cask docker")
            print("   # or download from https://www.docker.com/products/docker-desktop")
            print()
            print("Option B — Podman:")
            print("   brew install podman")
            print("   podman machine init && podman machine start")

        elif system == "windows":
            print("Option A — Docker Desktop:")
            print("   Download from https://www.docker.com/products/docker-desktop")
            print("   Note: requires Windows 10/11 with WSL2 enabled")
            print()
            print("Option B — Podman Desktop:")
            print("   Download from https://podman-desktop.io/")
        else:
            print(f"For {system}:")
            print("   Docker: https://docs.docker.com/engine/install/")
            print("   Podman: https://podman.io/docs/installation")

        print()
        print("After installation, verify your runtime:")
        print("   docker --version   # or")
        print("   podman --version")
        print("="*60)

    def _disable_sandbox_mode(self) -> bool:
        """
        Update the config.yaml file to disable sandbox mode.

        Returns:
            bool: True if successful, False otherwise
        """
        import yaml
        from pathlib import Path

        try:
            # Find the config.yaml file (should be in the repo root)
            config_path = Path(__file__).resolve().parents[2] / "config.yaml"

            if not config_path.exists():
                self.logger.error(f"Config file not found at {config_path}")
                return False

            # Read current config
            with open(config_path, 'r') as f:
                config_data = yaml.safe_load(f)

            # Update the sandbox setting
            if 'analysis' not in config_data:
                config_data['analysis'] = {}
            if 'execution' not in config_data['analysis']:
                config_data['analysis']['execution'] = {}

            config_data['analysis']['execution']['sandbox'] = False

            # Write back to file
            with open(config_path, 'w') as f:
                yaml.dump(config_data, f, default_flow_style=False, sort_keys=False)

            self.logger.info("Successfully disabled sandbox mode in config.yaml")
            return True

        except Exception as e:
            self.logger.error(f"Failed to update config.yaml: {e}")
            return False

    def _get_error_data(self, execution_dir: Path) -> Optional[Dict[str, str]]:
        """
        Get error data from stderr.txt file.
        
        Args:
            execution_dir: Directory where error files might be
            
        Returns:
            Dictionary with error data or None if no error file found
        """
        # Only use stderr.txt per requirements
        stderr_file = execution_dir / "stderr.txt"
        
        error_data = None
        
        if stderr_file.exists():
            try:
                # Read the stderr file
                with open(stderr_file, 'r') as f:
                    stderr_content = f.read()
                
                if stderr_content.strip():
                    error_data = {
                        "error": stderr_content,
                        "traceback": stderr_content  # Use the full stderr as the traceback
                    }
                    self.logger.info(f"Loaded error from stderr.txt")
            except Exception as e:
                self.logger.error(f"Error reading stderr.txt: {e}")
        
        return error_data
    
    def _detect_and_install_missing_modules(self, stderr: str, max_attempts: int = 3) -> bool:
        """
        Detect missing modules from stderr and attempt to install them.
        
        Args:
            stderr: Standard error output from script execution
            max_attempts: Maximum number of installation attempts
            
        Returns:
            bool: True if at least one module was successfully installed, False otherwise
        """
        if not stderr:
            return False
            
        # When using an existing conda environment, we might not want to install packages
        # since they should already be available. Let's check if we're using an existing environment.
        use_existing_venv = self.config.get("execution", {}).get("use_existing_venv", False)
        
        if use_existing_venv and self.env_path:
            self.logger.warning(f"Module installation attempted in existing environment {self.env_path}")
            print(f"[AUTOINTERP] WARNING: Attempting to install modules in existing environment: {self.env_path}")
            print(f"[AUTOINTERP] Consider installing missing modules manually in your environment")
            
        if self.env_path is None:
            self.logger.warning("No virtual environment available for module installation")
            print(f"[AUTOINTERP] WARNING: No virtual environment available for module installation")
            return False
            
        # Enhanced error pattern detection
        import re
        
        # Pattern 1: Standard ModuleNotFoundError
        module_patterns = [
            r"ModuleNotFoundError: No module named '([^']+)'",
            r"ImportError: No module named '([^']+)'", 
            r"ImportError: cannot import name '([^']+)'",
            r"ImportError: No module named ([^\s\n]+)",
            r"import ([^\s\n]+).*ImportError",
            r"from ([^\s\.\n]+).*ImportError"
        ]
        
        missing_modules = set()
        
        # Extract all missing modules
        for pattern in module_patterns:
            matches = re.findall(pattern, stderr, re.IGNORECASE)
            for match in matches:
                # Clean up the module name
                module_name = match.strip().strip("'\"").split('.')[0]  # Get root module
                if module_name and not module_name.startswith('_'):
                    missing_modules.add(module_name)
        
        if not missing_modules:
            return False
            
        # Comprehensive mapping of module names to pip install names  
        pip_module_map = {
            # Machine Learning & AI
            "sklearn": "scikit-learn",
            "scikit_learn": "scikit-learn",
            "cv2": "opencv-python",
            "PIL": "Pillow",
            "Image": "Pillow",
            
            # Data & Visualization
            "plotly": "plotly",
            "bokeh": "bokeh",
            "altair": "altair",
            
            # Natural Language Processing
            "spacy": "spacy",
            "nltk": "nltk", 
            "textblob": "textblob",
            "gensim": "gensim",
            
            # Deep Learning
            "torchvision": "torchvision",
            "tensorflow": "tensorflow",
            "tf": "tensorflow",
            "keras": "keras",
            
            # Utilities
            "requests": "requests",
            "bs4": "beautifulsoup4",
            "lxml": "lxml",
            "openpyxl": "openpyxl",
            "yaml": "PyYAML",
            "dateutil": "python-dateutil",
            "dotenv": "python-dotenv"
        }
        
        pip_path = Path(self.env_path) / "bin" / "pip"
        if sys.platform.startswith('win'):
            pip_path = Path(self.env_path) / "Scripts" / "pip"
            
        installed_any = False
        
        for missing_module in missing_modules:
            pip_module = pip_module_map.get(missing_module, missing_module)
            
            print(f"[AUTOINTERP] Attempting to install missing module: {missing_module} -> {pip_module}")
            self.logger.info(f"Installing missing module: {missing_module} -> {pip_module}")
            
            # Try multiple installation strategies
            strategies = [
                [str(pip_path), "install", pip_module],
                [str(pip_path), "install", "--verbose", pip_module],
                [str(pip_path), "install", "--upgrade", pip_module],
                [str(pip_path), "install", "--no-cache-dir", pip_module]
            ]
            
            success = False
            for attempt, cmd in enumerate(strategies):
                if attempt >= max_attempts:
                    break
                    
                try:
                    print(f"[AUTOINTERP] Installation attempt {attempt + 1}: {' '.join(cmd)}")
                    result = subprocess.run(cmd, capture_output=True, text=True, timeout=300)
                    
                    if result.returncode == 0:
                        print(f"[AUTOINTERP] Successfully installed {pip_module}")
                        self.logger.info(f"Successfully installed {pip_module}")
                        success = True
                        installed_any = True
                        break
                    else:
                        print(f"[AUTOINTERP] Installation attempt {attempt + 1} failed: {result.stderr[:200]}...")
                        self.logger.warning(f"Installation attempt {attempt + 1} failed for {pip_module}")
                        
                except Exception as e:
                    print(f"[AUTOINTERP] Installation attempt {attempt + 1} exception: {str(e)}")
                    self.logger.error(f"Installation attempt {attempt + 1} exception for {pip_module}: {str(e)}")
            
            if not success:
                print(f"[AUTOINTERP] Failed to install {pip_module} after {max_attempts} attempts")
                self.logger.error(f"Failed to install {pip_module} after {max_attempts} attempts")
        
        return installed_any
    
    def _collect_visualization_files(self, script_dir: Path) -> List[str]:
        """
        Collect any visualization files generated during script execution.
        
        Args:
            script_dir: Directory where the script was executed
            
        Returns:
            List of paths to generated visualization files
        """
        visualization_extensions = ['.png', '.jpg', '.jpeg', '.svg', '.pdf', '.eps', '.ps', '.tiff', '.bmp']
        visualization_files = []
        
        try:
            for file_path in script_dir.iterdir():
                if file_path.is_file() and file_path.suffix.lower() in visualization_extensions:
                    visualization_files.append(str(file_path))
                    self.logger.info(f"Found visualization file: {file_path}")
        except Exception as e:
            self.logger.warning(f"Error collecting visualization files from {script_dir}: {e}")
        
        return visualization_files
    
    def _build_docker_wrapper_script(self,
                                     script_path: Path,
                                     parameters: Optional[Dict[str, Any]] = None) -> str:
        """
        Create the Python wrapper script that will run inside the Docker container.
        
        Args:
            script_path: Path to the original generated analysis script
            parameters: Optional parameters passed to the script
            
        Returns:
            Wrapper script content as a string
        """
        parameters_json = json.dumps(parameters or {})
        requirements_file = str(self.requirements_file.resolve()) if self.requirements_file.exists() else ""
        
        standard_imports_literal = json.dumps(self.STANDARD_IMPORTS)
        wrapper = f"""import sys
import io
import os
import subprocess
import json
from contextlib import redirect_stdout, redirect_stderr

CACHE_DIR = os.environ.get("AUTOINTERP_DOCKER_CACHE", "/autointerp_cache")
PIP_TARGET = os.environ.get("AUTOINTERP_PIP_TARGET", os.path.join(CACHE_DIR, "site-packages"))
REQUIREMENTS_SENTINEL = os.environ.get("AUTOINTERP_REQUIREMENTS_SENTINEL")
REQUIREMENTS_FILE = os.environ.get("AUTOINTERP_REQUIREMENTS_FILE", "{requirements_file}")

def _ensure_pythonpath():
    if PIP_TARGET and PIP_TARGET not in sys.path:
        sys.path.insert(0, PIP_TARGET)

def _install_requirements():
    if not REQUIREMENTS_FILE or not os.path.exists(REQUIREMENTS_FILE):
        print("[AUTOINTERP-DOCKER] Requirements file missing or not set: " + str(REQUIREMENTS_FILE), flush=True)
        return
    
    os.makedirs(PIP_TARGET, exist_ok=True)
    print("[AUTOINTERP-DOCKER] Installing requirements into " + str(PIP_TARGET), flush=True)
    try:
        subprocess.check_call([sys.executable, "-m", "pip", "install", "--upgrade", "pip"], stdout=sys.stdout, stderr=sys.stderr)
    except Exception:
        # Non-fatal - continue with existing pip version
        pass
    
    install_cmd = [
        sys.executable, "-m", "pip", "install",
        "-r", REQUIREMENTS_FILE,
        "--target", PIP_TARGET
    ]
    print("[AUTOINTERP-DOCKER] Running pip install command: " + str(install_cmd), flush=True)
    subprocess.check_call(install_cmd, stdout=sys.stdout, stderr=sys.stderr)
    
    if REQUIREMENTS_SENTINEL:
        with open(REQUIREMENTS_SENTINEL, "w") as sentinel_file:
            sentinel_file.write("ok")
    try:
        installed = os.listdir(PIP_TARGET)
        print("[AUTOINTERP-DOCKER] PIP_TARGET contents after install: " + str(installed), flush=True)
    except Exception as list_exc:
        print("[AUTOINTERP-DOCKER] Unable to list PIP_TARGET: " + str(list_exc), flush=True)

def prepare_environment():
    _ensure_pythonpath()
    if REQUIREMENTS_SENTINEL and os.path.exists(REQUIREMENTS_SENTINEL):
        return
    
    try:
        _install_requirements()
    except Exception as install_exc:
        # Ensure sentinel is removed if installation fails
        if REQUIREMENTS_SENTINEL and os.path.exists(REQUIREMENTS_SENTINEL):
            try:
                os.remove(REQUIREMENTS_SENTINEL)
            except OSError:
                pass
        raise install_exc


def main():
    prepare_environment()
    _ensure_pythonpath()
    try:
        import importlib
        importlib.import_module("numpy")
    except Exception as debug_exc:
        print("[AUTOINTERP-DOCKER] numpy import failed before executing script: " + str(debug_exc), file=sys.stderr)
        print("[AUTOINTERP-DOCKER] sys.path: " + str(sys.path), file=sys.stderr)
        raise
    
    script_path = r"{str(script_path)}"
    stdout_capture = io.StringIO()
    stderr_capture = io.StringIO()
    
    with open(script_path, 'r') as f:
        script_content = f.read()
    
    STANDARD_IMPORTS = {standard_imports_literal}
    script_content = STANDARD_IMPORTS + "\\n" + script_content
    
    script_content = script_content.replace('```python', '')
    script_content = script_content.replace('```', '')
    
    script_dir = os.path.dirname(os.path.abspath(script_path))
    if script_dir and script_dir not in sys.path:
        sys.path.insert(0, script_dir)
    
    globals_dict = {{"__file__": script_path, "__name__": "__main__", "parameters": {parameters_json}}}
    
    with redirect_stdout(stdout_capture), redirect_stderr(stderr_capture):
        exec(script_content, globals_dict)
        sys.stdout.flush()
        sys.stderr.flush()
    
    print(stdout_capture.getvalue())
    if stderr_capture.getvalue():
        print(stderr_capture.getvalue(), file=sys.stderr)


if __name__ == "__main__":
    try:
        main()
    except Exception as exc:
        import traceback
        tb = traceback.format_exc()
        print(f"Error: {{str(exc)}}", file=sys.stderr)
        print(tb, file=sys.stderr)
        sys.exit(1)
"""
        return textwrap.dedent(wrapper)
    
    def _gather_docker_env(self) -> List[str]:
        """
        Gather environment variable flags for Docker execution.
        
        Returns:
            List of -e ENV=value entries
        """
        hf_home = os.environ.get("HF_HOME", str(self.hf_cache_dir))
        transformers_cache = os.environ.get("TRANSFORMERS_CACHE", hf_home)
        huggingface_hub_cache = os.environ.get("HUGGINGFACE_HUB_CACHE", hf_home)
        env_names = {
            "HF_HOME",
            "TRANSFORMERS_CACHE",
            "HUGGINGFACE_HUB_CACHE",
            "HF_TOKEN",
            "HUGGINGFACEHUB_API_TOKEN",
            "OPENAI_API_KEY",
            "OPENROUTER_API_KEY",
            "ANTHROPIC_API_KEY",
            "CUDA_VISIBLE_DEVICES",
        }
        env_names.update(self.docker_env_passthrough)
        
        env_flags: List[str] = []
        critical_envs = {
            "HF_HOME": hf_home,
            "TRANSFORMERS_CACHE": transformers_cache,
            "HUGGINGFACE_HUB_CACHE": huggingface_hub_cache,
        }

        for key, value in critical_envs.items():
            env_flags.extend(["-e", f"{key}={value}"])
            env_names.discard(key)
        for name in env_names:
            if name in os.environ:
                env_flags.extend(["-e", f"{name}={os.environ[name]}"])
        
        env_flags.extend([
            "-e", f"AUTOINTERP_DOCKER_CACHE={self.docker_cache_root}",
            "-e", f"AUTOINTERP_PIP_TARGET={self.docker_requirements_target}",
            "-e", f"AUTOINTERP_REQUIREMENTS_SENTINEL={self.docker_requirements_sentinel}",
            "-e", f"AUTOINTERP_REQUIREMENTS_FILE={self.requirements_file.resolve()}",
        ])
        
        pythonpath_entries = []
        if "PYTHONPATH" in os.environ and os.environ["PYTHONPATH"]:
            pythonpath_entries.append(os.environ["PYTHONPATH"])
        pythonpath_entries.append(str(self.docker_requirements_target))
        pythonpath_entries.append(str(self.repo_root))
        env_flags.extend(["-e", f"PYTHONPATH={os.pathsep.join(pythonpath_entries)}"])
        
        return env_flags
    
    def _gather_docker_volumes(self, script_dir: Path) -> List[str]:
        """
        Collect volume mounts for docker run invocation.
        
        Args:
            script_dir: Directory containing the script to run
            
        Returns:
            List of -v volume specifications
        """
        volumes = set()
        resolved_script_dir = script_dir.resolve()
        resolved_project_dir = self.path_resolver.get_project_dir().resolve()
        ensure_directory(resolved_project_dir)
        resolved_repo_root = self.repo_root.resolve()
        
        volumes.add(f"{resolved_project_dir}:{resolved_project_dir}")
        volumes.add(f"{resolved_script_dir}:{resolved_script_dir}")
        if resolved_repo_root.exists():
            volumes.add(f"{resolved_repo_root}:{resolved_repo_root}:ro")
        
        # Cache directories
        cache_dirs = {
            self.hf_cache_dir,
            self.transformers_cache_dir,
            self.pip_cache_dir,
            self.torch_cache_dir,
            self.docker_cache_root,
        }
        
        for cache_dir in cache_dirs:
            cache_dir.mkdir(parents=True, exist_ok=True)
            volumes.add(f"{cache_dir}:{cache_dir}")
        
        volume_flags: List[str] = []
        for volume in sorted(volumes):
            # On Podman + SELinux enforcing, append :z so the container
            # gets the correct SELinux label for bind-mounted paths.
            if self.selinux_enforcing:
                if volume.endswith(":ro"):
                    volume = volume + ",z"
                elif ":" in volume and not volume.endswith(":z"):
                    volume = volume + ":z"
            volume_flags.extend(["-v", volume])

        return volume_flags
    
    def _build_docker_command(self,
                              script_dir: Path,
                              wrapper_name: str,
                              prefer_gpu: bool = True) -> Tuple[List[str], bool]:
        """
        Construct the docker run command for executing the wrapper script.
        
        Args:
            script_dir: Directory containing the generated script and wrapper
            wrapper_name: Name of the wrapper script file
            prefer_gpu: Whether to attempt GPU pass-through
            
        Returns:
            Tuple of (docker command list, gpu_enabled flag)
        """
        cmd: List[str] = [self.container_runtime, "run", "--rm"]
        cmd.extend(["-w", str(script_dir.resolve())])

        # Run as current user when possible to avoid root-owned artifacts
        if hasattr(os, "getuid"):
            if self.is_podman:
                # Podman: map host UID into the container's user namespace
                cmd.extend(["--userns=keep-id"])
            else:
                cmd.extend(["--user", f"{os.getuid()}:{os.getgid()}"])

        gpu_requested = prefer_gpu and (self.docker_use_gpu or bool(os.environ.get("CUDA_VISIBLE_DEVICES")))
        gpu_enabled = False
        if gpu_requested:
            if self.is_podman:
                # Podman uses CDI (Container Device Interface) for GPU access
                cmd.extend(["--device", "nvidia.com/gpu=all"])
            else:
                cmd.extend(["--gpus", "all"])
            gpu_enabled = True
        
        cmd.extend(self.docker_extra_args)
        cmd.extend(self._gather_docker_env())
        cmd.extend(self._gather_docker_volumes(script_dir))
        cmd.append(self.docker_image)
        cmd.extend(["python", "-u", wrapper_name])
        return cmd, gpu_enabled
    
    async def _execute_in_docker(self,
                                 script_path: Path,
                                 parameters: Optional[Dict[str, Any]] = None,
                                 execution_type: str = "analysis") -> Dict[str, Any]:
        """
        Execute the generated script inside a Docker container.
        
        Args:
            script_path: Path to the generated analysis script
            parameters: Optional parameters for the script
            execution_type: Type of execution ("analysis" or "visualization")
            
        Returns:
            Dictionary with execution results
        """
        script_path = script_path.resolve()
        script_dir = script_path.parent
        os.makedirs(script_dir, exist_ok=True)
        
        wrapper_name = "__autointerp_wrapper.py"
        wrapper_path = script_dir / wrapper_name
        
        wrapper_code = self._build_docker_wrapper_script(script_path, parameters)
        wrapper_path.write_text(wrapper_code, encoding="utf-8")
        
        docker_cmd, gpu_enabled = self._build_docker_command(script_dir, wrapper_name, prefer_gpu=True)
        self.logger.info(f"Executing {execution_type} script in {self.container_runtime}: {' '.join(docker_cmd)}")
        
        try:
            process = await asyncio.create_subprocess_exec(
                *docker_cmd,
                stdout=asyncio.subprocess.PIPE,
                stderr=asyncio.subprocess.PIPE
            )
            stdout_bytes, stderr_bytes = await process.communicate()
            stdout = stdout_bytes.decode("utf-8", errors="replace")
            stderr = stderr_bytes.decode("utf-8", errors="replace")
            return_code = process.returncode
            
            # Retry without GPU if the GPU flag caused the failure
            gpu_error_signatures = [
                "could not select device driver",
                "unknown flag: --gpus",
                "no CUDA-capable device is detected",
                # Podman CDI errors
                "CDI device",
                "unresolvable CDI",
                "nvidia.com/gpu",
            ]
            if return_code != 0 and gpu_enabled and any(sig in stderr for sig in gpu_error_signatures):
                self.logger.warning(f"{self.container_runtime} execution failed with GPU enabled, retrying without GPU access")
                retry_cmd, _ = self._build_docker_command(script_dir, wrapper_name, prefer_gpu=False)
                process = await asyncio.create_subprocess_exec(
                    *retry_cmd,
                    stdout=asyncio.subprocess.PIPE,
                    stderr=asyncio.subprocess.PIPE
                )
                stdout_bytes, stderr_bytes = await process.communicate()
                stdout = stdout_bytes.decode("utf-8", errors="replace")
                stderr = stderr_bytes.decode("utf-8", errors="replace")
                return_code = process.returncode
            
            with open(script_dir / "stdout.txt", "w", encoding="utf-8") as stdout_file:
                stdout_file.write(stdout)
            with open(script_dir / "stderr.txt", "w", encoding="utf-8") as stderr_file:
                stderr_file.write(stderr)
            
            return {
                "success": return_code == 0,
                "return_code": return_code,
                "stdout": stdout,
                "stderr": stderr,
                "output": stdout,
                "error": stderr if return_code != 0 else None,
                "results": {"stdout": stdout},
                "script_path": str(script_path)
            }
        finally:
            try:
                if wrapper_path.exists():
                    wrapper_path.unlink()
            except Exception as cleanup_exc:
                self.logger.warning(f"Failed to remove temporary wrapper script: {cleanup_exc}")
        
    def setup_virtual_environment(self):
        """
        Set up a virtual environment for analysis execution.
        This happens on demand when executing scripts.
        """
        # Import required modules at the beginning to avoid scoping issues
        import subprocess
        import shutil
        import time
        import os
        
        # If we already have a working env_path, just return immediately
        if hasattr(self, 'env_path') and self.env_path is not None and Path(self.env_path).exists():
            # Check if Python executable exists in the stored env_path
            python_path = Path(self.env_path) / "bin" / "python"
            if sys.platform.startswith('win'):
                python_path = Path(self.env_path) / "Scripts" / "python.exe"
                
            if python_path.exists():
                # Test if it works
                try:
                    test_result = subprocess.run(
                        [str(python_path), "-c", "print('venv test successful')"],
                        capture_output=True, text=True, timeout=30
                    )
                    if test_result.returncode == 0:
                        self.logger.info(f"Using existing virtual environment at {self.env_path}")
                        print(f"[AUTOINTERP] Using existing virtual environment at {self.env_path}")
                        return  # Already set up properly
                except Exception as e:
                    self.logger.error(f"Error testing existing environment: {str(e)}")
                    # If test fails, continue with setup

        # Auto-detect active virtual environment from environment variables
        # Check VIRTUAL_ENV (standard venvs) or CONDA_PREFIX (conda environments)
        active_venv = os.environ.get('VIRTUAL_ENV') or os.environ.get('CONDA_PREFIX')
        if active_venv:
            env_dir = Path(active_venv)
            python_path = env_dir / "bin" / "python"
            if sys.platform.startswith('win'):
                python_path = env_dir / "Scripts" / "python.exe"

            if python_path.exists():
                try:
                    test_result = subprocess.run(
                        [str(python_path), "-c", "print('venv test successful')"],
                        capture_output=True, text=True, timeout=30
                    )
                    if test_result.returncode == 0:
                        self.logger.info(f"Auto-detected active virtual environment at {env_dir}")
                        print(f"[AUTOINTERP] Auto-detected active virtual environment: {env_dir}")
                        self.env_path = str(env_dir)
                        return
                    else:
                        self.logger.warning(f"Active virtual environment test failed: {test_result.stderr}")
                except Exception as e:
                    self.logger.warning(f"Error testing active virtual environment: {str(e)}")

        # Check if we should use an existing virtual environment
        use_existing_venv = self.config.get("execution", {}).get("use_existing_venv", False)
        existing_venv_path = self.config.get("execution", {}).get("existing_venv_path", "")
        
        if use_existing_venv and existing_venv_path:
            # Resolve the existing venv path
            if existing_venv_path.startswith("/"):
                # Absolute path
                env_dir = Path(existing_venv_path)
            else:
                # Relative path - assume it's a conda/venv name or relative to home
                # First try as conda environment
                conda_base = os.environ.get('CONDA_PREFIX', '')
                if conda_base:
                    conda_envs_path = Path(conda_base).parent / "envs" / existing_venv_path
                    if conda_envs_path.exists():
                        env_dir = conda_envs_path
                    else:
                        # Try as venv in home directory
                        env_dir = Path.home() / existing_venv_path
                else:
                    # Try as venv in home directory
                    env_dir = Path.home() / existing_venv_path
            
            # Check if Python executable exists in the specified venv
            python_path = env_dir / "bin" / "python"
            if sys.platform.startswith('win'):
                python_path = env_dir / "Scripts" / "python.exe"
            
            if python_path.exists():
                # Test if it works
                try:
                    test_result = subprocess.run(
                        [str(python_path), "-c", "print('venv test successful')"],
                        capture_output=True, text=True, timeout=30
                    )
                    if test_result.returncode == 0:
                        self.logger.info(f"Using existing virtual environment at {env_dir}")
                        print(f"[AUTOINTERP] Using existing virtual environment at {env_dir}")
                        self.env_path = str(env_dir)
                        return
                    else:
                        print(f"[AUTOINTERP] Existing virtual environment test failed: {test_result.stderr}")
                except Exception as e:
                    print(f"[AUTOINTERP] Error testing existing virtual environment: {str(e)}")
            else:
                print(f"[AUTOINTERP] Python executable not found in specified venv: {python_path}")
            
            print(f"[AUTOINTERP] Falling back to creating new virtual environment")
        
        # Check if we should use the system Python instead of a virtual environment
        use_system_python = self.config.get("execution", {}).get("use_system_python", False)
        
        if use_system_python:
            self.logger.info("Using system Python as configured in settings")
            print(f"[AUTOINTERP] Using system Python instead of virtual environment")
            
            # Set env_path to None to indicate using system Python
            self.env_path = None
            return
            
        self.logger.info("Setting up virtual environment for analysis execution...")
        
        # Use force_clean_venv setting from config
        force_clean = self.config.get("execution", {}).get("force_clean_venv", False)
        self.logger.info(f"force_clean_venv setting: {force_clean}")
        
        # Set up paths for the virtual environment
        base_dir = Path.home() / ".autointerp"
        base_dir.mkdir(parents=True, exist_ok=True)
        env_dir = base_dir / "venv"
        
        # Check if Python executable exists in venv
        python_path = env_dir / "bin" / "python"
        if sys.platform.startswith('win'):
            python_path = env_dir / "Scripts" / "python.exe"
        
        # If force_clean is True, remove the existing venv
        if force_clean and env_dir.exists():
            try:
                import shutil
                print(f"[AUTOINTERP] Removing existing virtual environment at {env_dir}")
                self.logger.info(f"Removing existing virtual environment at {env_dir}")
                
                # First try to remove bin/python symlink to avoid potential permission issues
                try:
                    if python_path.exists() and python_path.is_symlink():
                        python_path.unlink()
                except Exception:
                    pass  # Ignore if we can't remove the symlink
                
                # Now remove the entire directory
                shutil.rmtree(env_dir, ignore_errors=True)
                # Ensure it's fully removed before continuing
                import time
                time.sleep(2)  # Longer delay to ensure filesystem operations complete
                
                # Double-check removal
                if env_dir.exists():
                    print(f"[AUTOINTERP] Warning: Virtual environment directory still exists after removal attempt")
            except Exception as e:
                self.logger.error(f"Error removing existing virtual environment: {e}")
                print(f"[AUTOINTERP] Error removing existing virtual environment: {e}")
        
        # Check if we can reuse the existing venv
        if env_dir.exists() and python_path.exists() and not force_clean:
            # Test if the existing venv works
            try:
                print(f"[AUTOINTERP] Testing existing virtual environment at {env_dir}")
                self.logger.info(f"Testing existing virtual environment at {env_dir}")
                
                test_result = subprocess.run(
                    [str(python_path), "-c", "print('venv test successful')"],
                    capture_output=True,
                    text=True,
                    timeout=30
                )
                
                if test_result.returncode == 0:
                    print(f"[AUTOINTERP] Reusing existing virtual environment at {env_dir}")
                    self.logger.info(f"Reusing existing virtual environment at {env_dir}")
                    self.env_path = str(env_dir)
                    return
                else:
                    print(f"[AUTOINTERP] Existing virtual environment test failed with return code {test_result.returncode}")
                    print(f"[AUTOINTERP] Error output: {test_result.stderr}")
            except Exception as e:
                print(f"[AUTOINTERP] Existing virtual environment test failed with exception: {str(e)}")
                # If test fails, we'll create a new venv below
        
        # If we get here and force_clean is False, print a clear message about why we need a new venv
        if not force_clean and env_dir.exists():
            print(f"[AUTOINTERP] Cannot reuse existing virtual environment - test failed")
        
        # If we get here, we need to create a new venv
        print(f"[AUTOINTERP] Creating a new virtual environment using Python module venv with --copies option")
        start_time = time.time()
        
        try:
            # Use a direct call to create a venv with copies instead of symlinks
            base_dir = Path.home() / ".autointerp"
            base_dir.mkdir(parents=True, exist_ok=True)
            env_dir = base_dir / "venv"
            
            # Create the venv with --copies to avoid symlinks to system Python
            creation_result = subprocess.run(
                [sys.executable, "-m", "venv", "--copies", str(env_dir)],
                capture_output=True,
                text=True,
                timeout=180
            )
            
            if creation_result.returncode != 0:
                raise Exception(f"venv creation failed: {creation_result.stderr}")
                
            # Manually verify venv creation
            python_path = env_dir / "bin" / "python"
            if sys.platform.startswith('win'):
                python_path = env_dir / "Scripts" / "python.exe"
                
            if not python_path.exists():
                raise Exception(f"Python executable missing in created venv: {python_path}")
                
            # Test the Python interpreter to ensure it works
            test_result = subprocess.run(
                [str(python_path), "-c", "print('venv test successful')"],
                capture_output=True,
                text=True,
                timeout=30
            )
            
            if test_result.returncode != 0:
                raise Exception(f"venv Python test failed: {test_result.stderr}")
                
            # Display how long it took to create the venv
            end_time = time.time()
            elapsed = end_time - start_time
            print(f"[AUTOINTERP] Virtual environment created in {elapsed:.2f} seconds")
            
            success = True
            env_path = str(env_dir)
            error_msg = ""
            
        except Exception as e:
            success = False
            env_path = ""
            error_msg = str(e)
        
        if not success:
            self.logger.error(f"Failed to create virtual environment: {error_msg}")
            print(f"[AUTOINTERP] Failed to create virtual environment: {error_msg}")
            print(f"[AUTOINTERP] Falling back to system Python")
            self.env_path = None
            return
            
        self.logger.info(f"Created virtual environment at {env_path}")
        print(f"[AUTOINTERP] Created virtual environment at {env_path}")
        self.env_path = env_path
        
        # Install required packages in the virtual environment
        requirements_file = self.requirements_file
        
        print(f"[AUTOINTERP] Installing required packages in virtual environment...")
        self.logger.info(f"Installing required packages in virtual environment...")
        
        # Upgrade pip first to avoid issues
        try:
            pip_path = Path(env_path) / "bin" / "pip" if not sys.platform.startswith('win') else Path(env_path) / "Scripts" / "pip"
            subprocess.run([str(pip_path), "install", "--upgrade", "pip", "setuptools", "wheel"], 
                          check=True, capture_output=True, text=True)
            print(f"[AUTOINTERP] Successfully upgraded pip in the virtual environment")
        except Exception as e:
            print(f"[AUTOINTERP] Warning: Failed to upgrade pip: {e}")
        
        if requirements_file.exists():
            print(f"[AUTOINTERP] Using requirements file: {requirements_file}")
            success, error_msg = install_requirements(env_path, requirements_file)
        else:
            print(f"[AUTOINTERP] Using default packages list")
            success, error_msg = install_requirements(env_path)
            
        if not success:
            self.logger.error(f"Failed to install requirements: {error_msg}")
            print(f"[AUTOINTERP] Failed to install requirements: {error_msg}")
            
            # Don't fall back to system Python - that defeats the purpose of isolation
            # Instead, try to fix specific packages that commonly cause issues
            print(f"[AUTOINTERP] Attempting targeted fixes for common packages...")
            
            # Try installing nltk specifically since it's a common issue
            pip_path = env_path / "bin" / "pip" if not sys.platform.startswith('win') else env_path / "Scripts" / "pip"
            nltk_cmd = [str(pip_path), "install", "--verbose", "nltk"]
            try:
                nltk_result = subprocess.run(nltk_cmd, capture_output=True, text=True, timeout=180)
                if nltk_result.returncode == 0:
                    print(f"[AUTOINTERP] Successfully installed nltk package")
                else:
                    print(f"[AUTOINTERP] Failed to install nltk package: {nltk_result.stderr}")
            except Exception as e:
                print(f"[AUTOINTERP] Exception installing nltk: {str(e)}")
                
            # Install other critical packages
            for pkg in ["transformers", "torch"]:
                print(f"[AUTOINTERP] Installing critical package {pkg}...")
                try:
                    pkg_cmd = [str(pip_path), "install", "--verbose", pkg]
                    pkg_result = subprocess.run(pkg_cmd, capture_output=True, text=True, timeout=180)
                    if pkg_result.returncode == 0:
                        print(f"[AUTOINTERP] Successfully installed {pkg} package")
                    else:
                        print(f"[AUTOINTERP] Failed to install {pkg} package: {pkg_result.stderr}")
                except Exception as e:
                    print(f"[AUTOINTERP] Exception installing {pkg}: {str(e)}")
            
            # Continue instead of returning/failing - we'll handle missing modules at runtime
            
        # Verify critical packages are installed correctly
        try:
            # Check for key packages
            packages_to_verify = ["scikit-learn"]
            missing_packages = []
            
            for package in packages_to_verify:
                # Convert package name to directory name (scikit-learn -> sklearn)
                pkg_dir = "sklearn" if package == "scikit-learn" else package.replace("-", "_")
                
                # Check if package directory exists in site-packages
                if sys.platform.startswith('win'):
                    site_packages = list(Path(env_path).glob(f"Lib/site-packages/{pkg_dir}"))
                else:
                    site_packages = list(Path(env_path).glob(f"lib/python*/site-packages/{pkg_dir}"))
                
                if site_packages:
                    self.logger.info(f"Verified {package} is installed at: {site_packages[0]}")
                else:
                    missing_packages.append(package)
            
            # Install any missing packages
            if missing_packages:
                print(f"[AUTOINTERP] Installing missing packages: {', '.join(missing_packages)}")
                pip_path = Path(env_path) / "bin" / "pip" if not sys.platform.startswith('win') else Path(env_path) / "Scripts" / "pip"
                
                for package in missing_packages:
                    print(f"[AUTOINTERP] Installing {package}...")
                    subprocess.check_call([str(pip_path), "install", package])
                
                print(f"[AUTOINTERP] Successfully installed missing packages")
            else:
                print(f"[AUTOINTERP] All required packages already installed")
                
        except Exception as e:
            print(f"[AUTOINTERP] Warning: Package verification failed: {e}")
            print(f"[AUTOINTERP] Will try to continue anyway...")
            
        self.logger.info("Successfully installed required packages in virtual environment")
        print(f"[AUTOINTERP] Successfully installed required packages in virtual environment")
    
    async def execute_analysis(self, 
                          script_path: Union[str, Path], 
                          question: Dict[str, Any],
                          parameters: Optional[Dict[str, Any]] = None,
                          execution_type: str = "analysis") -> Dict[str, Any]:
        """
        Execute an analysis or visualization script and capture the results.
        
        Args:
            script_path: Path to the analysis script
            question: Question dictionary to analyze
            parameters: Optional parameters to pass to the analysis script
            execution_type: Type of execution ("analysis" or "visualization")
            
        Returns:
            Dictionary with execution results
        """
        script_path = Path(script_path)
        if not script_path.exists():
            return {
                "success": False,
                "error": f"Analysis script not found: {script_path}",
                "results": None,
                "execution_time": 0
            }
        
        # Execute the script directly without creating duplicate files
        start_time = time.time()
        try:
            if self.sandbox_enabled:
                results = await self._execute_in_docker(script_path, parameters, execution_type)
            else:
                results = await self._execute_script_directly(script_path, parameters, execution_type)
        except Exception as e:
            execution_time = time.time() - start_time
            return {
                "success": False,
                "error": f"Error executing analysis: {str(e)}",
                "traceback": traceback.format_exc(),
                "results": None,
                "execution_time": execution_time
            }
        
        execution_time = time.time() - start_time
        
        # Process and structure the results for the evaluator
        processed_results = self._process_results(results, question, execution_time, execution_type)
        
        # Add script path to the results for reference
        processed_results["script_path"] = str(script_path)
        
        return processed_results
    
    
    def _process_results(self, 
                       raw_results: Dict[str, Any], 
                       question: Dict[str, Any],
                       execution_time: float,
                       execution_type: str = "analysis") -> Dict[str, Any]:
        """
        Process and structure raw results for the evaluator.
        
        Args:
            raw_results: Raw execution results
            question: Question dictionary
            execution_time: Execution time in seconds
            execution_type: Type of execution ("analysis" or "visualization")
            
        Returns:
            Processed results dictionary
        """
        processed = {
            "success": raw_results.get("success", False),
            "execution_time": execution_time,
            "execution_time_formatted": format_time_elapsed(execution_time),
            "question": question,
            "timestamp": get_timestamp(),
            "execution_type": execution_type
        }
        
        # Include error information if execution failed
        if not processed["success"]:
            processed["error"] = raw_results.get("error", "Unknown error")
            processed["traceback"] = raw_results.get("traceback", "")
            return processed
        
        # Extract stdout as our primary results data
        stdout = raw_results.get("stdout", "")
        
        # Simply store the raw stdout without any parsing
        processed["results"] = {"stdout": stdout}
        
        # Add execution outputs
        processed["stdout"] = stdout
        processed["stderr"] = raw_results.get("stderr", "")
        
        # For visualizations, collect any generated image files
        if execution_type == "visualization" and "script_path" in raw_results:
            script_path = Path(raw_results["script_path"])
            script_dir = script_path.parent if script_path.exists() else None
            if script_dir:
                visualization_files = self._collect_visualization_files(script_dir)
                processed["visualization_files"] = visualization_files
        
        return processed
    
    async def _execute_script_directly(self, 
                                 script_path: Path, 
                                 parameters: Optional[Dict[str, Any]] = None,
                                 execution_type: str = "analysis") -> Dict[str, Any]:
        """
        Execute the analysis or visualization script directly without creating any duplicates or separate results folders.
        
        Args:
            script_path: Path to the script
            parameters: Optional parameters to pass to the script
            execution_type: Type of execution ("analysis" or "visualization")
            
        Returns:
            Dictionary with execution results
        """
        # Set up the virtual environment if it's not ready yet
        if not hasattr(self, 'env_path') or self.env_path is None:
            self.setup_virtual_environment()
            
        # If the setup failed, env_path will be None, which will use system Python
        if not hasattr(self, 'env_path') or self.env_path is None:
            self.logger.warning("Virtual environment not available, using system Python")
            print(f"[AUTOINTERP] Using system Python for execution")
        
        # Extract directory information from the script path
        script_path_obj = Path(script_path)
        script_dir = script_path_obj.parent
        
        # Use the same directory structure that was created by the AnalysisGenerator
        # The script should be in a directory like analysis/analysis_1/attempt_1/
        temp_dir = script_dir
        os.makedirs(temp_dir, exist_ok=True)
        
        # Determine the correct Python executable to use
        if self.env_path is None:
            # Use system Python
            python_executable = sys.executable
            print(f"[AUTOINTERP] Using system Python: {python_executable}")
        else:
            # Use the virtual environment Python
            env_path_obj = Path(self.env_path)
            if sys.platform.startswith('win'):
                python_executable = str(env_path_obj / "Scripts" / "python.exe")
            else:
                python_executable = str(env_path_obj / "bin" / "python")
            print(f"[AUTOINTERP] Using virtual environment Python: {python_executable}")
            
            # Verify the Python executable exists
            if not Path(python_executable).exists():
                self.logger.error(f"Python executable not found: {python_executable}")
                print(f"[AUTOINTERP] ERROR: Python executable not found: {python_executable}")
                # Fall back to system Python
                python_executable = sys.executable
                print(f"[AUTOINTERP] Falling back to system Python: {python_executable}")
        
        # Run the script directly using subprocess
        cmd = [
            python_executable, "-c",
            f"""
import sys
import io
import importlib.util
from contextlib import redirect_stdout, redirect_stderr
import json
import os

# Add standard imports first
{self.STANDARD_IMPORTS}

# Now run the original script
try:
    # Use file execution approach instead of module loading
    script_path = r"{script_path}"
    
    # Capture stdout/stderr using StringIO buffers
    stdout_capture = io.StringIO()
    stderr_capture = io.StringIO()
    
    # Execute the script directly using exec with redirected stdout/stderr
    with open(script_path, 'r') as f:
        script_content = f.read()

    # Clean the script content to remove markdown code fences
    # Remove ```python first (since it contains ```)
    script_content = script_content.replace('```python', '')
    # Then remove ```
    script_content = script_content.replace('```', '')

    # Add the script's directory to sys.path to ensure imports work
    script_dir = os.path.dirname(os.path.abspath(script_path))
    if script_dir not in sys.path:
        sys.path.insert(0, script_dir)
    
    # Create a globals dict with parameters
    globals_dict = {{"__file__": script_path, "__name__": "__main__", "parameters": {json.dumps(parameters or {})}}}
    
    # Force stdout flush after each print in the script
    sys.stdout.flush()
    sys.stderr.flush()
    
    # Execute with redirected stdout/stderr
    with redirect_stdout(stdout_capture), redirect_stderr(stderr_capture):
        exec(script_content, globals_dict)
        # Make sure all output is flushed
        sys.stdout.flush()
        sys.stderr.flush()
    
    # Print captured outputs to subprocess stdout/stderr
    print(stdout_capture.getvalue())
    if stderr_capture.getvalue():
        print(stderr_capture.getvalue(), file=sys.stderr)
    
    sys.exit(0)
    
except Exception as exc:
    import traceback
    tb = traceback.format_exc()
    print(f"Error: {{str(exc)}}", file=sys.stderr)
    print(tb, file=sys.stderr)
    sys.exit(1)
"""
        ]
        
        # Execute the command
        self.logger.info(f"Executing {execution_type} script directly: {script_path}")
        self.logger.info(f"Using Python executable: {python_executable}")
        print(f"[AUTOINTERP] Executing {execution_type} script: {script_path}")
        print(f"[AUTOINTERP] Python executable: {python_executable}")
        try:
            process = await asyncio.create_subprocess_exec(
                *cmd,
                stdout=asyncio.subprocess.PIPE,
                stderr=asyncio.subprocess.PIPE
            )
            
            stdout_bytes, stderr_bytes = await process.communicate()
            stdout = stdout_bytes.decode('utf-8', errors='replace')
            stderr = stderr_bytes.decode('utf-8', errors='replace')
            return_code = process.returncode
            
            # Write outputs to files for debugging and consistency with old approach
            with open(temp_dir / "stdout.txt", "w") as f:
                f.write(stdout)
            
            with open(temp_dir / "stderr.txt", "w") as f:
                f.write(stderr)
                
            # Enhanced automatic module installation and script retry
            if return_code != 0 and ("ModuleNotFoundError" in stderr or "ImportError" in stderr):
                self.logger.info(f"{execution_type.capitalize()} script failed with import error, attempting to install missing modules")
                print(f"[AUTOINTERP] Detected import error in {execution_type} execution, attempting automatic module installation...")
                
                # Use our enhanced detection and installation method
                if self._detect_and_install_missing_modules(stderr):
                    print(f"[AUTOINTERP] Retrying script execution after installing modules...")
                    self.logger.info(f"Retrying script execution after module installation")
                    
                    # Retry the script execution
                    process = await asyncio.create_subprocess_exec(
                        *cmd,
                        stdout=asyncio.subprocess.PIPE,
                        stderr=asyncio.subprocess.PIPE
                    )
                    
                    stdout_bytes, stderr_bytes = await process.communicate()
                    stdout = stdout_bytes.decode('utf-8', errors='replace')
                    stderr = stderr_bytes.decode('utf-8', errors='replace')
                    return_code = process.returncode
                    
                    # Write updated outputs to files
                    with open(temp_dir / "stdout.txt", "w") as f:
                        f.write(stdout)
                    
                    with open(temp_dir / "stderr.txt", "w") as f:
                        f.write(stderr)
                    
                    # If it still fails with import errors, try once more
                    if return_code != 0 and ("ModuleNotFoundError" in stderr or "ImportError" in stderr):
                        self.logger.info(f"Script still failing, trying one more module installation attempt")
                        print(f"[AUTOINTERP] Script still failing, attempting final module installation...")
                        
                        if self._detect_and_install_missing_modules(stderr):
                            print(f"[AUTOINTERP] Final retry of script execution...")
                            
                            # Final retry
                            process = await asyncio.create_subprocess_exec(
                                *cmd,
                                stdout=asyncio.subprocess.PIPE,
                                stderr=asyncio.subprocess.PIPE
                            )
                            
                            stdout_bytes, stderr_bytes = await process.communicate()
                            stdout = stdout_bytes.decode('utf-8', errors='replace')
                            stderr = stderr_bytes.decode('utf-8', errors='replace')
                            return_code = process.returncode
                            
                            # Write final outputs to files
                            with open(temp_dir / "stdout.txt", "w") as f:
                                f.write(stdout)
                            
                            with open(temp_dir / "stderr.txt", "w") as f:
                                f.write(stderr)
                else:
                    print(f"[AUTOINTERP] Could not automatically install missing modules")
                    self.logger.warning(f"Could not automatically install missing modules")
            
            # Log execution results
            self.logger.info(f"Script execution completed with return code: {return_code}")
            if return_code != 0:
                self.logger.error(f"Script execution failed: {stderr}")
            
            return {
                "success": return_code == 0,
                "return_code": return_code,
                "stdout": stdout,
                "stderr": stderr,
                "output": stdout,
                "error": stderr if return_code != 0 else None,
                "results": {"stdout": stdout},
                "script_path": str(script_path)
            }
            
        except Exception as ex:
            # Get the traceback information from the exception
            tb = traceback.format_exc()
            error_msg = f"Error executing script: {str(ex)}"
            self.logger.error(f"{error_msg}\n{tb}")
            
            # Write error to stderr.txt for consistency with the old approach
            with open(temp_dir / "stderr.txt", "w") as f:
                f.write(f"{error_msg}\n{tb}")
                
            return {
                "success": False,
                "error": error_msg,
                "traceback": tb,
                "stdout": "",
                "stderr": tb,
                "results": None
            }